export default [
    'pulse wave',
    'duty cycle',
    'arpeggio',
    '8-bit',
    'fakebit',
    '2a03',
    'dmg',
    'nanoloop',
    'hardware elitist',
    'famitracker',
    'slamdunk lifestyle',
    // 'armani prada gucci boyz',
    'anamanaguchi',
    'bleep',
    'bloop',
    'lofi',
    'mega man',
    'lsdj',
    'tracker',
    'game boy',
    'backlight mod',
    'pro sound',
    'white noise',
    'noise channel',
    'demoscene',
    'wav channel',
    'keygen',
    'vrc6',
    'magfest',
    'sawtooth',
    'cartridge',
    'trash80',
    'waveform',
    'vibrato',
    'pitch bend',
    'chip music',
    'commodore 64',
    'atari',
    'sid chip',
    'portamento',
    'software',
    'analog',
    'blip blop',
    'circuit bending',
    'ymck',
    'aesthetic',
    'video game',
    'moe moe kyunstep',
    'electronic',
    'blip fest',
    'sound chip',
    'nostalgia',
    'nes',
    'amiga',
    'hexadecimal',
    'glitch',
    'trey frey',
    'ultrasyd',
    'nintendocore',
    'sequencer',
    'milkytracker',
    'renoise',
    'bit crush',
    'indie scene',
    'brooklyn warehouse',
    'bweeew',
    // '',
];